# Generated by Django 4.0.2 on 2022-02-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_cusfeed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cusfeed',
        ),
    ]
