# Generated by Django 4.0.2 on 2022-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_delete_cusfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='cusfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('date', models.DateField(null=True)),
                ('place', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
