# Generated by Django 4.0.2 on 2022-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_cusfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='userbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('place', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('guest', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('checkin', models.DateField(null=True)),
                ('checkout', models.DateField(null=True)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
