# Generated by Django 4.0.2 on 2022-02-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='place',
            new_name='newplace',
        ),
    ]
