# Generated by Django 4.0.2 on 2022-02-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_rename_place_places_newplace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='places',
        ),
    ]
