# Generated by Django 4.0.2 on 2022-02-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_addplaces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userbook',
        ),
    ]
