# Generated by Django 4.0.2 on 2022-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_userbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cnumber', models.CharField(max_length=16)),
                ('expmonth', models.CharField(max_length=10)),
                ('expyear', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=10)),
            ],
        ),
    ]
